### ISSUE TITLE
Can't delete some images

### ISSUE THREAD

**Issue by rstacruz** [Ragnarson/deis-cleanup#2]
Using a stateless deis 1.12.3, some images can't be deleted because it's in use. The containers should be removed first.

```
Error response from daemon: Conflict, cannot delete 9a654fb551d6 because the container 11379f004d9f is using it, use -f to force
Error: failed to remove images: [10.xx.yy.zz:5000/production:v45]
```

The command used was:

```
docker run \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v /var/lib/docker:/var/lib/docker \
 --rm \
 twobox/deis-cleanup
```

**Comment by szymonpk** [comment]
It's expected behavior when some images are still in use. Did it broke whole cleanup run for you? Or just didn't remove some image(s).

You could investigate it by running `docker inspect <id>`, your image may be dependency of another running image and it won't be removed.

**Comment by rstacruz** [comment]
doing a DRY_RUN tells me they're versions that were already retired (eg, `production:v50` is latest, but `v45` can be deleted).

**Comment by szymonpk** [comment]
Oh, sorry (friday was busy day :() ok now I see what is going on. There is no code to remove exited containers. I'll create issue in our internal pivotal, unfortunately I can't say when this will be handled.
